<?php

namespace Database\Seeders;

use App\Models\Setting;
use Illuminate\Database\Seeder;

class SettingsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('settings')->delete();




        $data = [
            [
                'id' => 1,
                'name' => 'slot_duration',
                'val' => '00:15',
                'type' => 'text',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2025-02-19 13:24:07',
                'updated_at' => '2025-02-19 13:24:07',
                'deleted_at' => NULL,
            ],
            [
                'id' => 2,
                'name' => 'app_name',
                'val' => 'Frezka Saas',
                'type' => 'general',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2025-02-19 13:42:25',
                'updated_at' => '2025-02-19 13:42:25',
                'deleted_at' => NULL,
            ],
            [
                'id' => 3,
                'name' => 'footer_text',
                'val' => 'Builttt with ♥ from <a href="https://iqonic.design" target="_blank">IQONIC DESIGN.</a>',
                'type' => 'general',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2025-02-19 13:42:25',
                'updated_at' => '2025-02-19 13:42:25',
                'deleted_at' => NULL,
            ],
            [
                'id' => 4,
                'name' => 'helpline_number',
                'val' => '5265897485',
                'type' => 'general',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2025-02-19 13:42:25',
                'updated_at' => '2025-02-19 13:42:25',
                'deleted_at' => NULL,
            ],
            [
                'id' => 5,
                'name' => 'copyright_text',
                'val' => 'Copyright © 2025',
                'type' => 'general',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2025-02-19 13:42:25',
                'updated_at' => '2025-02-19 13:42:25',
                'deleted_at' => NULL,
            ],
            [
                'id' => 6,
                'name' => 'ui_text',
                'val' => 'UI Powered By <a href="https://hopeui.iqonic.design/" target="_blank">HOPE UI</a>',
                'type' => 'general',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2025-02-19 13:42:25',
                'updated_at' => '2025-02-19 13:42:25',
                'deleted_at' => NULL,
            ],
            [
                'id' => 7,
                'name' => 'inquriy_email',
                'val' => 'hello@iqonic.design',
                'type' => 'general',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2025-02-19 13:42:25',
                'updated_at' => '2025-02-19 13:42:25',
                'deleted_at' => NULL,
            ],
            [
                'id' => 8,
                'name' => 'site_description',
                'val' => 'Dummy Text',
                'type' => 'general',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2025-02-19 13:42:25',
                'updated_at' => '2025-02-19 13:42:25',
                'deleted_at' => NULL,
            ],
            [
                'id' => 9,
                'name' => 'logo',
                'val' =>  asset('/images/logo/frezka.png'),
                'type' => 'string',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2025-02-19 13:42:25',
                'updated_at' => '2025-02-19 13:42:25',
                'deleted_at' => NULL,
            ],
            [
                'id' => 10,
                'name' => 'mini_logo',
                'val' => asset('/images/logo/mini_logo.png'),
                'type' => 'string',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2025-02-19 13:42:25',
                'updated_at' => '2025-02-19 13:42:25',
                'deleted_at' => NULL,
            ],
            [
                'id' => 11,
                'name' => 'dark_logo',
                'val' => asset('/images/logo/dark_logo.png'),
                'type' => 'string',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2025-02-19 13:42:25',
                'updated_at' => '2025-02-19 13:42:25',
                'deleted_at' => NULL,
            ],
            [
                'id' => 12,
                'name' => 'dark_mini_logo',
                'val' => asset('/images/logo/mini_logo.png'),
                'type' => 'string',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2025-02-19 13:42:25',
                'updated_at' => '2025-02-19 13:42:25',
                'deleted_at' => NULL,
            ],
            [
                'id' => 13,
                'name' => 'favicon',
                'val' => asset('/images/logo/mini_logo.png'),
                'type' => 'string',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2025-02-19 13:42:25',
                'updated_at' => '2025-02-19 13:42:25',
                'deleted_at' => NULL,
            ],
            [
                'id' => 14,
                'name' => 'bussiness_address_line_1',
                'val' => '123 Main St',
                'type' => 'string',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2025-02-19 13:42:25',
                'updated_at' => '2025-02-19 13:42:25',
                'deleted_at' => NULL,
            ],

            [
                'id' => 15,
                'name' => 'app_name',
                'val' => 'Frezka Saas',
                'type' => 'general',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2025-02-19 13:42:25',
                'updated_at' => '2025-02-19 13:42:25',
                'deleted_at' => NULL,
            ],
            [
                'id' => 16,
                'name' => 'footer_text',
                'val' => 'Builttt with ♥ from <a href="https://iqonic.design" target="_blank">IQONIC DESIGN.</a>',
                'type' => 'general',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2025-02-19 13:42:25',
                'updated_at' => '2025-02-19 13:42:25',
                'deleted_at' => NULL,
            ],
            [
                'id' => 17,
                'name' => 'helpline_number',
                'val' => '5265897485',
                'type' => 'general',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2025-02-19 13:42:25',
                'updated_at' => '2025-02-19 13:42:25',
                'deleted_at' => NULL,
            ],
            [
                'id' => 18,
                'name' => 'copyright_text',
                'val' => 'Copyright © 2025',
                'type' => 'general',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2025-02-19 13:42:25',
                'updated_at' => '2025-02-19 13:42:25',
                'deleted_at' => NULL,
            ],
            [
                'id' => 19,
                'name' => 'ui_text',
                'val' => 'UI Powered By <a href="https://hopeui.iqonic.design/" target="_blank">HOPE UI</a>',
                'type' => 'general',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2025-02-19 13:42:25',
                'updated_at' => '2025-02-19 13:42:25',
                'deleted_at' => NULL,
            ],
            [
                'id' => 20,
                'name' => 'inquriy_email',
                'val' => 'hello@iqonic.design',
                'type' => 'general',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2025-02-19 13:42:25',
                'updated_at' => '2025-02-19 13:42:25',
                'deleted_at' => NULL,
            ],
            [
                'id' => 21,
                'name' => 'site_description',
                'val' => 'Discover effortless beauty bookings with expert stylists, exclusive offers, and a seamless experience — all from one smart platform.',
                'type' => 'general',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2025-02-19 13:42:25',
                'updated_at' => '2025-02-19 13:42:25',
                'deleted_at' => NULL,
            ],
            [
                'id' => 22,
                'name' => 'logo',
                'val' =>  asset('/images/logo/frezka.png'),
                'type' => 'string',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2025-02-19 13:42:25',
                'updated_at' => '2025-02-19 13:42:25',
                'deleted_at' => NULL,
            ],
            [
                'id' => 23,
                'name' => 'mini_logo',
                'val' => asset('/images/logo/mini_logo.png'),
                'type' => 'string',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2025-02-19 13:42:25',
                'updated_at' => '2025-02-19 13:42:25',
                'deleted_at' => NULL,
            ],
            [
                'id' => 24,
                'name' => 'dark_logo',
                'val' => asset('/images/logo/dark_logo.png'),
                'type' => 'string',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2025-02-19 13:42:25',
                'updated_at' => '2025-02-19 13:42:25',
                'deleted_at' => NULL,
            ],
            [
                'id' => 25,
                'name' => 'dark_mini_logo',
                'val' => asset('/images/logo/mini_logo.png'),
                'type' => 'string',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2025-02-19 13:42:25',
                'updated_at' => '2025-02-19 13:42:25',
                'deleted_at' => NULL,
            ],
            [
                'id' => 26,
                'name' => 'favicon',
                'val' => asset('/images/logo/mini_logo.png'),
                'type' => 'string',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2025-02-19 13:42:25',
                'updated_at' => '2025-02-19 13:42:25',
                'deleted_at' => NULL,
            ],
            [
                'id' => 27,
                'name' => 'bussiness_address_line_1',
                'val' => '123 Main St',
                'type' => 'string',
                'created_by' => 2,
                'updated_by' => 2,
                'deleted_by' => NULL,
                'created_at' => '2025-02-19 13:42:25',
                'updated_at' => '2025-02-19 13:42:25',
                'deleted_at' => NULL,
            ],
            [
                'id' => 28,
                'name' => 'google_analytics',
                'val' => NULL,
                'type' => 'text',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2025-02-19 13:42:25',
                'updated_at' => '2025-02-19 13:42:25',
                'deleted_at' => NULL,
            ],
            [
                'id' => 29,
                'name' => 'default_language',
                'val' => 'en',
                'type' => 'misc',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2025-02-19 13:42:25',
                'updated_at' => '2025-02-19 13:42:25',
                'deleted_at' => NULL,
            ],
            [
                'id' => 30,
                'name' => 'default_time_zone',
                'val' => 'Asia/Kolkata',
                'type' => 'misc',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2025-02-19 13:42:25',
                'updated_at' => '2025-02-19 13:42:25',
                'deleted_at' => NULL,
            ],
            [
                'id' => 31,
                'name' => 'data_table_limit',
                'val' => '5',
                'type' => 'misc',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2025-02-19 13:42:25',
                'updated_at' => '2025-02-19 13:42:25',
                'deleted_at' => NULL,
            ],
            [
                'id' => 32,
                'name' => 'date_format',
                'val' => 'Y-m-d',
                'type' => 'misc',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2025-02-19 13:42:25',
                'updated_at' => '2025-02-19 13:42:25',
                'deleted_at' => NULL,
            ],
            [
                'id' => 33,
                'name' => 'time_format',
                'val' => 'H:i',
                'type' => 'misc',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2025-02-19 13:42:25',
                'updated_at' => '2025-02-19 13:42:25',
                'deleted_at' => NULL,
            ],
            [
                'id' => 34,
                'name' => 'is_demo_login',
                'val' => '1',
                'type' => 'integaration',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'created_at' => '2025-02-19 13:42:25',
                'updated_at' => '2025-02-19 13:42:25',
                'deleted_at' => NULL,
            ]
        ];


        foreach ($data as $item) {
            // Store setting in the database
            $setting = Setting::create([
                'id' => $item['id'],
                'name' => $item['name'],
                'val' => $item['val'],
                'type' => $item['type'],
                'created_by' => $item['created_by'],
                'updated_by' => $item['updated_by'],
                'deleted_by' => $item['deleted_by'],
                'created_at' => $item['created_at'],
                'updated_at' => $item['updated_at'],
                'deleted_at' => $item['deleted_at'],
            ]);

            // If setting is for an image, attach it to media
            if (in_array($item['name'], ['logo', 'mini_logo', 'dark_logo', 'dark_mini_logo', 'favicon'])) {
                $this->attachImageToMedia($setting, $item['val']);
            }
        }
    }

    private function attachImageToMedia($model, $publicPath)
    {


        if (!file_exists($publicPath)) {
            return false;
        }

        $file = new \Illuminate\Http\File($publicPath);

        return $model->addMedia($file)->preservingOriginal()->toMediaCollection('image');
    }
}
