<?php
return [
    'name' => 'MenuBuilder',
    'MENU' => [
        'menu_type' => 'vertical',
        'menu_item_type' => 'link',
        'title' => '',
        'short_title' => '-',
        'is_route' => true,
        'route' => null,
        'url' => null,
        'active' => null,
        'order' => 0,
        'menu_level' => 0,
        'start_icon' => null,
        'end_icon' => null,
        'parent_id' => null,
        'link_class' => '',
        'item_class' => '',
        'permission' => [],
        'role' => [],
        'is_tooltip' => false,
        'is_disabled' => false,
    ],
    'ARRAY_MENU' => [
        [
            'title' => 'sidebar.main',
            'menu_item_type' => 'static',
            'permission' => ['view_dashboard', 'view_booking'],
            'order' => 0,
        ],
        [
            'start_icon' => 'fa-solid fa-gauge',
            'title' => 'sidebar.dashboard',
            'route' => 'backend.home',
            'permission' => ['view_dashboard'],
            'active' => ['app', 'app/dashboard'],
            'order' => 1,
        ],
        [
            'start_icon' => 'fa-solid fa-calendar-days',
            'title' => 'sidebar.calendar_bookings',
            'route' => 'backend.bookings.index',
            'active' => ['app/bookings'],
            'permission' => ['view_booking'],
            'order' => 2,
        ],
        [
            'title' => 'sidebar.company',
            'menu_item_type' => 'static',
            'permission' => ['booking_booking_tableview', 'view_branch', 'view_service'],
            'order' => 3,
        ],
        [
            'start_icon' => 'fa-solid fa-code-branch',
            'title' => 'sidebar.branches',
            'route' => 'backend.branch.index',
            'active' => ['app/branch'],
            'permission' => ['view_branch'],
            'order' => 4,
        ],
        [
            'start_icon' => 'fa-solid fa-calendar-days',
            'title' => 'sidebar.bookings',
            'route' => 'backend.bookings.datatable_view',
            'active' => ['app/bookings-table-view'],
            'permission' => ['booking_booking_tableview'],
            'order' => 5,
        ],
        [
            'start_icon' => 'fa-brands fa-servicestack',
            'title' => 'sidebar.services',
            'nickname' => 'service',
            'menu_item_type' => 'parent',
            'permission' => ['view_service'],
            'order' => 6,
            'children' => [
                [
                    'title' => 'sidebar.list',
                    'route' => 'backend.services.index',
                    'active' => ['app/services'],
                    'permission' => ['view_service'],
                    'order' => 0,
                    'menu_level' => 1,
                ],
                [
                    'title' => 'sidebar.categories',
                    'route' => 'backend.categories.index',
                    'active' => ['app/categories'],
                    'permission' => ['view_category'],
                    'order' => 1,
                    'menu_level' => 1,
                ],
                [
                    'title' => 'sidebar.sub_categories',
                    'route' => 'backend.categories.index_nested',
                    'active' => ['app/sub-categories'],
                    'permission' => ['view_subcategory'],
                    'order' => 2,
                    'menu_level' => 1,
                ],
            ],
        ],
        // [
        //     'start_icon' => 'fa-solid fa-cubes',
        //     'title' => 'sidebar.package',
        //     'route' => 'backend.package.index',
        //     'active' => ['app/package'],
        //     'permission' => ['view_package'],
        //     'order' => 7,
        // ],
        // [
        //     'start_icon' => 'fa-solid fa-people-carry-box',
        //     'title' => 'sidebar.customer_packages',
        //     'route' => 'backend.clientPackage',
        //     'active' => ['app/client-package'],
        //     'permission' => ['view_package'],
        //     'order' => 7,
        // ],
        [
            'title' => 'sidebar.users',
            'menu_item_type' => 'static',
            'permission' => ['view_customer', 'view_staff', 'view_review'],
            'order' => 9,
        ],
        [
            'start_icon' => 'fa-solid fa-address-card',
            'title' => 'sidebar.staffs',
            'route' => 'backend.employees.index',
            'active' => ['app/employees'],
            'permission' => ['view_staff'],
            'order' => 10,
        ],
        [
            'start_icon' => 'fa-solid fa-users',
            'title' => 'sidebar.customers',
            'route' => 'backend.customers.index',
            'active' => ['app/customers'],
            'permission' => ['view_customer'],
            'order' => 11,
        ],
        [
            'start_icon' => 'fa-solid fa-star',
            'title' => 'sidebar.reviews',
            'route' => 'backend.employees.review',
            'active' => ['app/employees-review'],
            'permission' => ['view_review'],
            'order' => 12,
        ],
        [
            'title' => 'sidebar.finance',
            'menu_item_type' => 'static',
            'permission' => ['view_tax', 'view_staff_earning'],
            'order' => 13,
        ],
        [
            'start_icon' => 'fa-solid fa-money-bill-trend-up',
            'title' => 'sidebar.tax',
            'route' => 'backend.tax.index',
            'active' => ['app/tax'],
            'permission' => ['view_tax'],
            'order' => 14,
        ],
        [
            'start_icon' => 'fa-solid fa-money-bill-1-wave',
            'title' => 'sidebar.staff_earnings',
            'route' => 'backend.earnings.index',
            'active' => ['app/earnings'],
            'permission' => ['view_staff_earning'],
            'order' => 15,
        ],
        [
            'start_icon' => 'fa-solid fa-ticket',
            'title' => 'promotion.coupon_title',
            'route' => 'backend.promotions.index',
            'active' => ['app/promotions'],
            'permission' => ['view_promotion'],
            'order' => 16,
            'menu_level' => 1,
        ],
        [
            'title' => 'sidebar.reports',
            'menu_item_type' => 'static',
            'permission' => ['view_report', 'view_staff_payout', 'view_staff_service'],
            'order' => 17,
        ],
        [
            'start_icon' => 'fa-solid fa-file-invoice-dollar',
            'title' => 'sidebar.daily_bookings',
            'route' => 'backend.reports.daily-booking-report',
            'active' => ['app/daily-booking-report'],
            'permission' => ['view_report'],
            'order' => 18,
        ],
        [
            'start_icon' => 'fa-solid fa-chart-line',
            'title' => 'sidebar.overall_bookings',
            'route' => 'backend.reports.overall-booking-report',
            'active' => ['app/overall-booking-report'],
            'permission' => ['view_report'],
            'order' => 19,
        ],
        [
            'start_icon' => 'fa-solid fa-chart-bar',
            'title' => 'sidebar.staffs_payouts',
            'route' => 'backend.reports.payout-report',
            'active' => ['app/payout-report'],
            'permission' => ['view_staff_payout'],
            'order' => 20,
        ],
        [
            'start_icon' => 'fa-solid fa-clipboard-user',
            'title' => 'sidebar.staffs_services',
            'route' => 'backend.reports.staff-report',
            'active' => ['app/staff-report'],
            'permission' => ['view_staff_service'],
            'order' => 21,
        ],
        [
            'title' => 'sidebar.system',
            'menu_item_type' => 'static',
            'permission' => ['setting_general', 'setting_misc', 'setting_quick_booking', 'setting_custom_code', 'setting_customization', 'setting_mail', 'setting_notification', 'setting_intigrations', 'setting_custom_fields', 'setting_currency', 'setting_commission', 'setting_holiday', 'setting_bussiness_hours', 'setting_payment_method', 'setting_language', 'setting_menu_builder', 'view_page', 'view_app_banner', 'view_access_control'],
            'order' => 22,
        ],
        [
            'start_icon' => 'fa-solid fa-gear',
            'title' => 'sidebar.settings',
            'route' => 'backend.settings',
            'active' => 'app/settings',
            'permission' => ['view_setting'],
            'order' => 23,
        ],
        [
            'start_icon' => 'fa fa-cogs',
            'title' => 'sidebar.frontend_settings',
            'route' => 'frontendsetting.index',
            'active' => 'app/frontend-settings',
            'permission' => ['view_setting'],
            'order' => 24,
        ],

        [
            'start_icon' => 'fa fa-list',
            'title' => 'sidebar.users_inquiries',
            'route' => 'backend.inquiries.index',
            'active' => 'app/inquiries',
            'permission' => ['view_user_inquiry'],
            'order' => 25,
        ],


        [
            'start_icon' => 'fa-solid fa-question-circle',
            'title' => 'sidebar.lbl_faq',
            'route' => 'backend.faq.index',
            'active' => 'app/faqs',
            'permission' => ['view_faq'],
            'order' => 26,
        ],

        [
            'start_icon' => 'fa-solid fa-blog',
            'title' => 'sidebar.lbl_blog',
            'route' => 'backend.blog.index',
            'active' => 'app/blogs',
            'permission' => ['view_blog'],
            'order' => 27,
        ],
        [
            'start_icon' => 'fa-solid fa-file',
            'title' => 'sidebar.pages',
            'route' => 'backend.pages.index',
            'active' => ['app/pages'],
            'permission' => ['view_page'],
            'order' => 24,
        ],
        [
            'start_icon' => 'fa-solid fa-bell',
            'title' => 'sidebar.notifications',
            'nickname' => 'notifications',
            'order' => 25,
            'permission' => ['view_notification', 'view_notification_template'],
            'menu_item_type' => 'parent',
            'children' => [
                [
                    'title' => 'sidebar.list',
                    'route' => 'backend.notifications.index',
                    'active' => 'app/notifications',
                    'permission' => ['view_notification'],
                    'order' => 0,
                    'menu_level' => 1,
                ],
                [
                    'title' => 'sidebar.templates',
                    'route' => 'backend.notification-templates.index',
                    'active' => 'app/notification-templates*',
                    'permission' => ['view_notification_template'],
                    'order' => 1,
                    'menu_level' => 1,
                ],
            ],
        ],
        [
            'start_icon' => 'fa fa-sliders',
            'title' => 'sidebar.app_banner',
            'route' => 'backend.app-banners.index',
            'active' => 'app/app-banners',
            'permission' => ['view_app_banner'],
            'order' => 26,
        ],
        [
            'start_icon' => 'fa-solid fa-user-shield',
            'title' => 'sidebar.access_control',
            'route' => 'backend.permission-role.list',
            'active' => ['app/permission-role'],
            'permission' => ['view_access_control'],
            'order' => 27,
        ],
        [
            'title' => 'sidebar.subscriptions',
            'order' => 28,
            'start_icon' => 'fa-solid fa-ticket',
            'nickname' => 'subscriptions',
            'menu_item_type' => 'parent', // Mark this as a parent item
            'children' => [
                [
                    'title' => 'sidebar.active_subscriptions',
                    'route' => 'backend.subscriptions.index',
                    'active' => ['app/subscriptions'],
                    'permission' => ['subscription_tableview'],
                    'order' => 0,
                    'menu_level' => 1,
                ],
                [
                    'title' => 'sidebar.pending_subscriptions',
                    'route' => 'backend.subscriptions.pending', // Adjust the route as needed
                    'active' => ['app/subscriptions/pending'],
                    'permission' => ['view_pending_subscriptions'], // Add appropriate permission
                    'order' => 1,
                    'menu_level' => 1,
                ],
                [
                    'title' => 'sidebar.expired_subscriptions',
                    'route' => 'backend.subscriptions.expired', // Adjust the route as needed
                    'active' => ['app/subscriptions/expired'],
                    'permission' => ['view_expired_subscriptions'], // Add appropriate permission
                    'order' => 2,
                    'menu_level' => 1,
                ],
            ],
        ],
        [
            'title' => 'sidebar.plans',
            'order' => 29,
            'start_icon' => 'fa-solid fa-layer-group',
            'nickname' => 'plans',
            'route' => 'backend.subscription.plans.index', // Add a route for the parent item if needed
            'active' => ['app/subscriptions/plans'], // Adjust active routes if necessary
            'permission' => ['plan_tableview'], // Add permissions if needed
        ],
        [
            'title' => 'sidebar.payments',
            'order' => 30,
            'start_icon' => 'fa-solid fa-credit-card',
            'nickname' => 'payments',
            'route' => 'backend.payment.index', // Route for the Payments menu item
            'active' => ['app/payments'], // Active route(s) for highlighting
            'permission' => ['manage_payments'], // Permission required to access this menu item
        ],
    ],
    'H_ARRAY_MENU' => [
        [
            'menu_type' => 'horizontal',
            'title' => 'sidebar.main',
            'menu_item_type' => 'parent',
            'permission' => ['view_dashboard', 'view_booking'],
            'order' => 0,
            'children' => [
                [
                    'menu_type' => 'horizontal',
                    'start_icon' => 'fa-solid fa-gauge',
                    'title' => 'sidebar.dashboard',
                    'route' => 'backend.home',
                    'active' => ['app', 'app/dashboard'],
                    'permission' => ['view_dashboard'],
                    'order' => 0,
                    'menu_level' => 1,
                ],
                [
                    'menu_type' => 'horizontal',
                    'start_icon' => 'fa-solid fa-calendar-days',
                    'title' => 'sidebar.calendar_bookings',
                    'route' => 'backend.bookings.index',
                    'active' => ['app/bookings'],
                    'permission' => ['view_booking'],
                    'order' => 1,
                    'menu_level' => 1,
                ],
            ],
        ],
        [
            'menu_type' => 'horizontal',
            'title' => 'sidebar.company',
            'menu_item_type' => 'parent',
            'order' => 1,
            'permission' => ['booking_booking_tableview', 'view_branch', 'view_service'],
            'children' => [
                [
                    'menu_type' => 'horizontal',
                    'start_icon' => 'fa-solid fa-code-branch',
                    'title' => 'sidebar.branches',
                    'route' => 'backend.branch.index',
                    'active' => ['app/branch'],
                    'permission' => ['view_branch'],
                    'order' => 0,
                    'menu_level' => 1,
                ],
                [
                    'menu_type' => 'horizontal',
                    'start_icon' => 'fa-solid fa-calendar-days',
                    'title' => 'sidebar.bookings',
                    'route' => 'backend.bookings.datatable_view',
                    'active' => ['app/bookings-table-view'],
                    'permission' => ['booking_booking_tableview'],
                    'order' => 1,
                    'menu_level' => 1,
                ],
                [
                    'menu_type' => 'horizontal',
                    'start_icon' => 'fa-brands fa-servicestack',
                    'title' => 'sidebar.services',
                    'nickname' => 'service',
                    'menu_item_type' => 'parent',
                    'order' => 2,
                    'menu_level' => 1,
                    'active' => ['app/services', 'app/categories', 'app/sub-categories'],
                    'permission' => ['view_service'],
                    'children' => [
                        [
                            'menu_type' => 'horizontal',
                            'title' => 'sidebar.list',
                            'route' => 'backend.services.index',
                            'active' => 'app/services',
                            'permission' => ['view_service'],
                            'order' => 0,
                            'menu_level' => 2,
                        ],
                        [
                            'menu_type' => 'horizontal',
                            'title' => 'sidebar.categories',
                            'route' => 'backend.categories.index',
                            'active' => 'app/categories',
                            'permission' => ['view_category'],
                            'order' => 1,
                            'menu_level' => 2,
                        ],
                        [
                            'menu_type' => 'horizontal',
                            'title' => 'sidebar.sub_categories',
                            'route' => 'backend.categories.index_nested',
                            'active' => 'app/sub-categories',
                            'permission' => ['view_subcategory'],
                            'order' => 2,
                            'menu_level' => 2,
                        ],
                    ],
                ],
                [
                    'start_icon' => 'fa-solid fa-cubes',
                    'title' => 'sidebar.package',
                    'route' => 'backend.package.index',
                    'active' => ['app/package'],
                    'permission' => ['view_package'],
                    'order' => 3,
                    'menu_level' => 1,
                ],
                [
                    'start_icon' => 'fa-solid fa-people-carry-box',
                    'title' => 'sidebar.customer_packages',
                    'route' => 'backend.clientPackage',
                    'active' => ['app/client-package'],
                    'permission' => ['view_package'],
                    'order' => 7,
                ],
            ],
        ],
        [
            'menu_type' => 'horizontal',
            'title' => 'sidebar.users',
            'menu_item_type' => 'parent',
            // 'permission' => ['view_customer', 'view_staff', 'view_review'],
            'permission' => ['view_customer', 'view_staff'],
            'order' => 2,
            'children' => [
                [
                    'menu_type' => 'horizontal',
                    'start_icon' => 'fa-solid fa-address-card',
                    'title' => 'sidebar.staffs',
                    'route' => 'backend.employees.index',
                    'active' => ['app/employees'],
                    'permission' => ['view_staff'],
                    'order' => 0,
                    'menu_level' => 1,
                ],
                [
                    'menu_type' => 'horizontal',
                    'start_icon' => 'fa-solid fa-users',
                    'title' => 'sidebar.customers',
                    'route' => 'backend.customers.index',
                    'active' => ['app/customers'],
                    'permission' => ['view_customer'],
                    'order' => 1,
                    'menu_level' => 1,
                ],
                [
                    'menu_type' => 'horizontal',
                    'start_icon' => 'fa-solid fa-star',
                    'title' => 'sidebar.reviews',
                    'route' => 'backend.employees.review',
                    'active' => ['app/employees-review'],
                    'permission' => ['view_review'],
                    'order' => 2,
                    'menu_level' => 1,
                ],
            ],
        ],
        [
            'menu_type' => 'horizontal',
            'title' => 'sidebar.finance',
            'menu_item_type' => 'parent',
            'order' => 3,
            'permission' => ['view_tax', 'view_staff_earning'],
            'children' => [
                [
                    'menu_type' => 'horizontal',
                    'start_icon' => 'fa-solid fa-money-bill-trend-up',
                    'title' => 'sidebar.tax',
                    'route' => 'backend.tax.index',
                    'active' => ['app/tax'],
                    'permission' => ['view_tax'],
                    'order' => 0,
                    'menu_level' => 1,
                ],
                [
                    'menu_type' => 'horizontal',
                    'start_icon' => 'fa-solid fa-money-bill-1-wave',
                    'title' => 'sidebar.staff_earnings',
                    'route' => 'backend.earnings.index',
                    'active' => ['app/earnings'],
                    'permission' => ['view_staff_earning'],
                    'order' => 1,
                    'menu_level' => 1,
                ],
                [
                    'start_icon' => 'fa-solid fa-ticket',
                    'title' => 'promotion.coupon_title',
                    'route' => 'backend.promotions.index',
                    'active' => ['app/promotions'],
                    'permission' => ['view_promotion'],
                    'order' => 2,
                    'menu_level' => 1,
                ],
            ],
        ],
        [
            'menu_type' => 'horizontal',
            'title' => 'sidebar.reports',
            'menu_item_type' => 'parent',
            'order' => 4,
            'permission' => ['view_report', 'view_staff_payout', 'view_staff_service'],
            'children' => [
                [
                    'menu_type' => 'horizontal',
                    'start_icon' => 'fa-solid fa-file-invoice-dollar',
                    'title' => 'sidebar.daily_bookings',
                    'route' => 'backend.reports.daily-booking-report',
                    'active' => ['app/daily-booking-report'],
                    'order' => 0,
                    'permission' => ['view_report'],
                    'menu_level' => 1,
                ],
                [
                    'menu_type' => 'horizontal',
                    'start_icon' => 'fa-solid fa-chart-line',
                    'title' => 'sidebar.overall_bookings',
                    'route' => 'backend.reports.overall-booking-report',
                    'active' => ['app/overall-booking-report'],
                    'order' => 1,
                    'permission' => ['view_report'],
                    'menu_level' => 1,
                ],
                [
                    'menu_type' => 'horizontal',
                    'start_icon' => 'fa-solid fa-chart-bar',
                    'title' => 'sidebar.staffs_payouts',
                    'route' => 'backend.reports.payout-report',
                    'active' => ['app/payout-report'],
                    'permission' => ['view_staff_payout'],
                    'order' => 2,
                    'menu_level' => 1,
                ],
                [
                    'menu_type' => 'horizontal',
                    'start_icon' => 'fa-solid fa-clipboard-user',
                    'title' => 'sidebar.staffs_services',
                    'route' => 'backend.reports.staff-report',
                    'active' => ['app/staff-report'],
                    'permission' => ['view_staff_service'],
                    'order' => 3,
                    'menu_level' => 1,
                ],
            ],
        ],
        [
            'menu_type' => 'horizontal',
            'title' => 'sidebar.system',
            'menu_item_type' => 'parent',
            'order' => 5,
            'permission' => ['view_setting', 'view_page', 'view_app_banner', 'view_access_control'],
            'children' => [
                [
                    'menu_type' => 'horizontal',
                    'start_icon' => 'fa-solid fa-gear',
                    'title' => 'sidebar.settings',
                    'route' => 'backend.settings',
                    'active' => 'app/settings',
                    'permission' => ['view_setting'],
                    'order' => 0,
                    'menu_level' => 1,
                ],

                [
                    'menu_type' => 'horizontal',
                    'start_icon' => 'fa-solid fa-file',
                    'title' => 'sidebar.pages',
                    'route' => 'backend.pages.index',
                    'active' => ['app/pages'],
                    'permission' => ['view_page'],
                    'order' => 1,
                    'menu_level' => 1,
                ],
                [
                    'menu_type' => 'horizontal',
                    'start_icon' => 'fa-solid fa-bell',
                    'title' => 'sidebar.notifications',
                    'nickname' => 'notifications',
                    'order' => 2,
                    'menu_level' => 1,
                    'menu_item_type' => 'parent',
                    'active' => ['app/notifications', 'app/notification-templates'],
                    'permission' => ['view_notification'],
                    'children' => [
                        [
                            'menu_type' => 'horizontal',
                            'title' => 'sidebar.list',
                            'route' => 'backend.notifications.index',
                            'active' => 'app/notifications',
                            'permission' => ['view_notification_list'],
                            'order' => 0,
                            'menu_level' => 2,
                        ],
                        [
                            'menu_type' => 'horizontal',
                            'title' => 'sidebar.templates',
                            'route' => 'backend.notification-templates.index',
                            'active' => 'app/notification-templates*',
                            'permission' => ['view_notification_template'],
                            'order' => 1,
                            'menu_level' => 2,
                        ],
                    ],
                ],
                [
                    'menu_type' => 'horizontal',
                    'start_icon' => 'fa fa-sliders',
                    'title' => 'sidebar.app_banner',
                    'route' => 'backend.app-banners.index',
                    'active' => 'app/app-banners',
                    'permission' => ['view_app_banner'],
                    'order' => 3,
                    'menu_level' => 1,
                ],

            ],
        ],
    ],
    'menu_routes' => [
        [
            'route' => 'backend.home',
            'title' => 'Dashboard',
        ],
        [
            'route' => 'backend.bookings.index',
            'title' => 'Calendar Bookings',
        ],
        [
            'route' => 'backend.branch.index',
            'title' => 'Branches',
        ],
        [
            'route' => 'backend.bookings.datatable_view',
            'title' => 'Bookings',
        ],
        [
            'route' => 'backend.services.index',
            'title' => 'Services List',
        ],
        [
            'route' => 'backend.categories.index',
            'title' => 'Categories',
        ],
        [
            'route' => 'backend.categories.index_nested',
            'title' => 'Sub Categories',
        ],
        [
            'route' => 'backend.employees.index',
            'title' => 'Staffs',
        ],
        [
            'route' => 'backend.customers.index',
            'title' => 'Customers',
        ],
        [
            'route' => 'backend.employees.review',
            'title' => 'Reviews',
        ],
        [
            'route' => 'backend.tax.index',
            'title' => 'Tax',
        ],
        [
            'route' => 'backend.earnings.index',
            'title' => 'Staff Earnings',
        ],
        [
            'route' => 'backend.reports.daily-booking-report',
            'title' => 'Daily Bookings',
        ],
        [
            'route' => 'backend.reports.overall-booking-report',
            'title' => 'Overall Bookings',
        ],
        [
            'route' => 'backend.reports.payout-report',
            'title' => 'Staffs Payouts',
        ],
        [
            'route' => 'backend.reports.staff-report',
            'title' => 'Staffs Services',
        ],
        [
            'route' => 'backend.settings',
            'title' => 'Settings',
        ],
        [
            'route' => 'backend.pages.index',
            'title' => 'Pages',
        ],
        [
            'route' => 'backend.notifications.index',
            'title' => 'List',
        ],
        [
            'route' => 'backend.notification-templates.index',
            'title' => 'Templates',
        ],
        [
            'route' => 'backend.app-banners.index',
            'title' => 'App Banner',
        ],
        [
            'route' => 'backend.permission-role.list',
            'title' => 'Access Control',
        ],
    ],
];
